spring:
  data:
    solr:
      host: http://192.168.77.137:8080/solr
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 192.168.77.137
    port: 5672
    username: java1809
    password: 123
    virtual-host: /java1809
dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
  protocol:
    port: 28802
server:
  port: 8081

