dubbo:
  application:
    name: item-service
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
  protocol:
    port: 28806
server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://10.36.138.36:3306/qf-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 192.168.77.137
    port: 5672
    username: java1809
    password: 123
    virtual-host: /java1809

html:
  locations: d://html//
