dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
  protocol:
    port: 28801
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root