dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
  protocol:
    port: 28808
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 10.36.8.8
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: java1809
