dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
  protocol:
    port: 28810
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v9
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 10.36.8.8
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: java1809
